<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class PaypalPlan  extends CI_Controller {

  public $secret;
  public $client;

  public function  __construct($secret, $client) {
    $this->secret = $secret;
    $this->client = $client;
  }

  public function index() {

  }

  public function getToken() {
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://api.sandbox.paypal.com/v1/oauth2/token');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, "grant_type=client_credentials");
    curl_setopt($ch, CURLOPT_USERPWD, 'ARu9gcMwFzhLz11FMKMjBNF7vGyH3uiP4al9h8pF936cRfEpMJrhlyHZre9JEaPt0gm1xLIh3NMYwAHL' . ':' . 'EL0sAFMZ-xu4tg5l6259I-Cn_5pt8-vwo1DjoxnhD1sb5UGorV2iluKGZyatgCdBRIu3mt38kNJ8LPSV');

    $headers = array();
    $headers[] = 'Accept: application/json';
    $headers[] = 'Accept-Language: en_US';
    $headers[] = 'Content-Type: application/x-www-form-urlencoded';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);

    return json_encode($result,true)->token;

  }

  public function createProduct() {
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://api.sandbox.paypal.com/v1/catalogs/products');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n  \"name\": \"Plan Service\",\n  \"description\": \"Plan service\",\n  \"type\": \"SERVICE\",\n  \"category\": \"SOFTWARE\",\n  \"home_url\": \"http://127.0.0.1/new-project/\"\n}");

    $headers = array();
    $headers[] = 'Content-Type: application/json';
    $headers[] = 'Authorization: Bearer A21AAJVeRAUu69xBbLtE3wDtIcrSe-2N1SOwGy3gyNip1HkwrUbVYmU2HY7qz2eGWdBMw4gdePJydE2GbbIx5u_TVsvqZ304Q';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);

    return json_encode($result);

  }

  public function createPlan() {
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, 'https://api.sandbox.paypal.com/v1/billing/plans');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n      \"product_id\": \"PROD-7C9484973A9562638\",\n      \"name\": \"Professional plan\",\n      \"description\": \"Professional plan\",\n      \"billing_cycles\": [\n        {\n          \"frequency\": {\n            \"interval_unit\": \"MONTH\",\n            \"interval_count\": 1\n          },\n          \"tenure_type\": \"TRIAL\",\n          \"sequence\": 1,\n          \"total_cycles\": 1\n        },\n        {\n          \"frequency\": {\n            \"interval_unit\": \"MONTH\",\n            \"interval_count\": 1\n          },\n          \"tenure_type\": \"REGULAR\",\n          \"sequence\": 2,\n          \"total_cycles\": 12,\n          \"pricing_scheme\": {\n            \"fixed_price\": {\n              \"value\": \"50\",\n              \"currency_code\": \"EUR\"\n            }\n          }\n        }\n      ],\n      \"payment_preferences\": {\n        \"auto_bill_outstanding\": true,\n        \"setup_fee\": {\n          \"value\": \"50\",\n          \"currency_code\": \"EUR\"\n        },\n        \"setup_fee_failure_action\": \"CONTINUE\",\n        \"payment_failure_threshold\": 3\n      },\n      \"taxes\": {\n        \"percentage\": \"10\",\n        \"inclusive\": false\n      }\n    }");

    $headers = array();
    $headers[] = 'Accept: application/json';
    $headers[] = 'Authorization: Bearer A21AAJVeRAUu69xBbLtE3wDtIcrSe-2N1SOwGy3gyNip1HkwrUbVYmU2HY7qz2eGWdBMw4gdePJydE2GbbIx5u_TVsvqZ304Q';
    $headers[] = 'Prefer: return=representation';
    $headers[] = 'Content-Type: application/json';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);

    return json_encode($result);
  }

  public function getCurrentTime() {
    return date('Y-m-d\\TH:i:s\\Z', time());
  }

  public function getApprovalURL($planid) {
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://api.sandbox.paypal.com/v1/billing/subscriptions');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);

    $time = $this->getCurrentTime();

    curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n      \"plan_id\": $planid,\n      \"start_time\": $time,\n      \"application_context\": {\n        \"brand_name\": \"Plan company\",\n        \"locale\": \"en-US\",\n        \"shipping_preference\": \"SET_PROVIDED_ADDRESS\",\n        \"user_action\": \"SUBSCRIBE_NOW\",\n        \"payment_method\": {\n          \"payer_selected\": \"PAYPAL\",\n          \"payee_preferred\": \"IMMEDIATE_PAYMENT_REQUIRED\"\n        },\n        \"return_url\": \"http://127.0.0.1/new-project/paypal/paypal_success\",\n        \"cancel_url\": \"http://127.0.0.1/new-project/paypal/paypal_cancel\"\n      }\n    }");

    $headers = array();
    $headers[] = 'Accept: application/json';
    $headers[] = 'Authorization: "Bearer "'.$this->getToken().'"';
    $headers[] = 'Prefer: return=representation';
    $headers[] = 'Content-Type: application/json';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);

    $reponse = json_encode($result, true);

    return $reponse->links[0]->href;

  }
}
